/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import static com.ID_generator.generateCustomerID;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.MouseInputAdapter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Joy
 */
public class addcustomer extends javax.swing.JFrame {
    int ProClick = 0;
    String filename=null;
    public static String ID = "";
    String path = null;
    String Email;
    Connection conn = null;
    //OraclePreparedStatement pst = null;
    OracleResultSet rs = null;

    /**
     * Creates new form addcustomer
     */
    public addcustomer(String nEmail) {
        
        
        
        Email = nEmail;
        initComponents();
        setPic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Customer_Name = new javax.swing.JTextField();
        Customer_Mobileno = new javax.swing.JTextField();
        Customer_Address = new javax.swing.JTextField();
        Customer_Password = new javax.swing.JTextField();
        Customer_Email = new javax.swing.JTextField();
        Add_Customer = new javax.swing.JButton();
        Customer_Gender = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        propic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imageAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Customer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 28, 109, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 22));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, 22));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 60, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, 22));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 60, 22));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, 22));

        Customer_Name.setBackground(new java.awt.Color(153, 153, 255));
        Customer_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Customer_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 30));

        Customer_Mobileno.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(Customer_Mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 30));

        Customer_Address.setBackground(new java.awt.Color(153, 153, 255));
        Customer_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Customer_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, 30));

        Customer_Password.setBackground(new java.awt.Color(153, 153, 255));
        Customer_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Customer_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 170, 30));

        Customer_Email.setBackground(new java.awt.Color(153, 153, 255));
        Customer_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Customer_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 170, 30));

        Add_Customer.setText("Register");
        Add_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_CustomerActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        Customer_Gender.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(Customer_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 110, 40));

        propic.setBackground(new java.awt.Color(204, 204, 255));
        propic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        propic.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                propicMouseDragged(evt);
            }
        });
        propic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                propicMousePressed(evt);
            }
        });
        jPanel1.add(propic, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jButton1.setText("Choose Profile Picture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 170, -1));

        imageAddress.setForeground(new java.awt.Color(0, 153, 255));
        imageAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(imageAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Customer_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_NameActionPerformed

    private void Add_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_CustomerActionPerformed
        // TODO add your handling code here:
        String user,gender,ext;
        try{
        conn = JavaConnectivity.ConnecrDb();
        
        PreparedStatement pst = conn.prepareStatement("INSERT INTO CUSTOMER(C_ID,C_NAME,C_MOBILENO,C_ADDRESS,C_GENDER,C_PASSWORD,C_EMAIL,MY_ROOM,CHECK_IN_TIME,PRO_PIC) VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
        
        if(ID.isEmpty())
        {
         //   System.out.println("1");
            ID = generateCustomerID(Email);
            pst.setString(1, this.ID);
        }
        else
        {
           // System.out.println("2");
            pst.setString(1, this.ID);
        }
        
            
        pst.setString(5, gender=Customer_Gender.getText());
        if(gender.equals("Male"))
        {
            ext = "Mr. ";
            filename = "C:\\Users\\Joy\\Documents\\NetBeansProjects\\DatabaseProject\\ProfilePictures\\male.jpg";
            
        }
        else
        {
            ext = "Ms. ";
            filename = "C:\\Users\\Joy\\Documents\\NetBeansProjects\\DatabaseProject\\ProfilePictures\\female.jpg";
            
        }
        pst.setString(2, user= ext+Customer_Name.getText());
        pst.setString(3, Customer_Mobileno.getText());
        pst.setString(4, Customer_Address.getText());
        pst.setString(6, Customer_Password.getText());
        pst.setString(7,  Customer_Email.getText());
        pst.setString(8,  "NULL");
        pst.setString(9,  "NULL");
        
            //System.out.println("1");
            
        if(!imageAddress.getText().isEmpty())
        {
            filename = imageAddress.getText();
            //System.out.println(filename);
        }
            //System.out.println(filename);
        
        pst.setString(10, filename);
            
            //System.out.println("2");
            
        pst.executeUpdate();
            
            //System.out.println("3");
            
            pst.close();
            conn.close();
            
            JOptionPane.showMessageDialog(null, user+",REGISTRATION SUCCESSFULL!");
            
            Customer_Name.setText(null);
            Customer_Mobileno.setText(null);
            Customer_Address.setText(null);
            Customer_Password.setText(null);
            Customer_Email.setText(null);
            Customer_Gender.setText(null);
            propic.setText(null);
            imageAddress.setText("");
            //setPic();
            
        
        }
        catch(Exception e){
            if(ProClick==1)
            {

    //delete previous image
                Path imagesPath = Paths.get(filename);

                try {
                    Files.delete(imagesPath);

                } catch (IOException ep) {
                    System.err.println("Unable to delete "+ imagesPath.toAbsolutePath().toString()+ " due to...");
                    e.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(null, "REGISTRATION FAILED");
           
        }
        
    }//GEN-LAST:event_Add_CustomerActionPerformed

    private void Customer_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_AddressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(new Login().status == 1)
        {
            Choice c = new Choice(Email);
            c.setVisible(true);
        }
        else if(new Login().status == 2)
        {
            Manager_Profile mp = new Manager_Profile(Email);
            mp.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Customer_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_EmailActionPerformed

    private void Customer_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_PasswordActionPerformed
    public static ImageIcon resize(ImageIcon im, int w, int h)
    {
        BufferedImage bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D gd = (Graphics2D)bi.createGraphics();
        gd.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING,RenderingHints.VALUE_RENDER_QUALITY));
        gd.drawImage(im.getImage(), 0, 0, w, h, null);
        gd.dispose();
        
        return new ImageIcon(bi);
    }
    
    public static int w=0,h=0;
    
    public void setPic()
    {
        filename = "C:\\Users\\Joy\\Documents\\NetBeansProjects\\DatabaseProject\\ProfilePictures\\default.png";
        propic.setIcon(resize(new ImageIcon(filename),171, 220));
    }
    public static void getScaledDimension(Dimension imgSize, Dimension boundary) {

    int original_width = imgSize.width;
    int original_height = imgSize.height;
    int bound_width = boundary.width;
    int bound_height = boundary.height;
    int new_width = original_width;
    int new_height = original_height;

    // first check if we need to scale width
    if (original_width > bound_width) {
        //scale width to fit
        new_width = bound_width;
        //scale height to maintain aspect ratio
        new_height = (new_width * original_height) / original_width;
    }

    // then check if we need to scale even with the new height
    if (new_height > bound_height) {
        //scale height to fit instead
        new_height = bound_height;
        //scale width to maintain aspect ratio
        new_width = (new_height * original_width) / original_height;
    }
    w= new_width;
    h= new_height;
    //return new Dimension(new_width, new_height);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            // TODO add your handling code here:
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            
            filename = f.getAbsolutePath();
            
            
            
            Image getAbsolutePath = null;
            
            ImageIcon icon = new ImageIcon(filename);

            //Image image = icon.getImage().getScaledInstance(propic.getWidth(), propic.getHeight(), Image.SCALE_SMOOTH);
            //propic.setIcon(resize(new ImageIcon(filename),propic.getWidth(), propic.getHeight()));
            
            /*
            Image img1 = resize(new ImageIcon(filename),propic.getWidth(), propic.getHeight()).getImage();
            Image img2 = img1.getScaledInstance(propic.getWidth(), propic.getHeight(), Image.SCALE_SMOOTH);
            
            ImageIcon icon = new ImageIcon(img2);
            */
            
            
            Dimension imgSize = new Dimension(icon.getImage().getWidth(chooser), icon.getImage().getHeight(chooser));
            Dimension boundary = new Dimension(171, 220);
            getScaledDimension(imgSize, boundary);
            
            
            Image img1 = resize(new ImageIcon(filename),w, h).getImage();
            Image img2 = img1.getScaledInstance(w, h, Image.SCALE_SMOOTH);
            
            ImageIcon icon1 = new ImageIcon(img2);
            
            propic.setBounds(390, 40, w, h);
            propic.setIcon(icon1);
            

        //writing
        
        BufferedImage bi = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = bi.createGraphics();
        // Draw img into bi so we can write it to file.
        g2.drawImage(img2, 0, 0, null);
        g2.dispose();
        
            // Now bi contains the img.
            // Note: img may have transparent pixels in it; if so, okay.
            // If not and you can use TYPE_INT_RGB you will get better
            // performance with it in the jvm.
        try {
            if(ID.isEmpty())
            {
             //   System.out.println(ID);
                ID = generateCustomerID(Email);
               // System.out.println(ID);
            }
            
            //System.out.println("writing ID = "+ID);
            ImageIO.write(bi, "jpg", new File(path = ("C:\\Users\\Joy\\Documents\\NetBeansProjects\\DatabaseProject\\ProfilePictures\\"+ID+".jpg")));
            filename = path;
            imageAddress.setText(filename);
            //System.out.println("222");
           ProClick = 1; 
        } catch (IOException ex) {
            Logger.getLogger(addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void propicMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propicMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_propicMouseDragged

    private void propicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propicMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_propicMousePressed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new addcustomer("").setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Customer;
    private javax.swing.JTextField Customer_Address;
    private javax.swing.JTextField Customer_Email;
    private javax.swing.JTextField Customer_Gender;
    private javax.swing.JTextField Customer_Mobileno;
    private javax.swing.JTextField Customer_Name;
    private javax.swing.JTextField Customer_Password;
    private javax.swing.JLabel imageAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel propic;
    // End of variables declaration//GEN-END:variables
}
