/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import static com.ID_generator.generateManagerID;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;

/**
 *
 * @author Joy
 */
public class addmanager extends javax.swing.JFrame {
    
    Connection conn = null;
    //OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    String Email;

    /**
     * Creates new form addmanager
     */
    public addmanager(String nEmail) {
        Email = nEmail;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Add_Customer = new javax.swing.JButton();
        Manager_Email = new javax.swing.JTextField();
        Manager_Password = new javax.swing.JTextField();
        Manager_Address = new javax.swing.JTextField();
        Manager_Mobileno = new javax.swing.JTextField();
        Manager_Name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 28, 109, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 87, 78, 22));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 78, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 78, 22));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 78, 22));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 78, 22));

        Add_Customer.setText("Register");
        Add_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_CustomerActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 80, -1));

        Manager_Email.setBackground(new java.awt.Color(153, 153, 255));
        Manager_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Manager_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 146, 22));

        Manager_Password.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(Manager_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 146, 22));

        Manager_Address.setBackground(new java.awt.Color(153, 153, 255));
        Manager_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Manager_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 146, 22));

        Manager_Mobileno.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(Manager_Mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 146, 22));

        Manager_Name.setBackground(new java.awt.Color(153, 153, 255));
        Manager_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Manager_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 87, 146, 22));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 90, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_CustomerActionPerformed
        // TODO add your handling code here:
        //String user,gender,ext;
        try{
            conn = JavaConnectivity.ConnecrDb();
            System.out.println("1");

            PreparedStatement pst = conn.prepareStatement("INSERT INTO MANAGER(M_ID,M_NAME,M_PHONE,M_ADDRESS,M_EMAIL,M_PASSWORD) VALUES(?, ?, ?, ?, ?, ?)");

           
            pst.setString(1, generateManagerID(Email));
            pst.setString(2, Manager_Name.getText());
            pst.setString(3, Manager_Mobileno.getText());
            pst.setString(4, Manager_Address.getText());
            pst.setString(5,  Manager_Email.getText());
            pst.setString(6, Manager_Password.getText());
            

            pst.executeUpdate();

            pst.close();
            conn.close();

            JOptionPane.showMessageDialog(null, "REGISTRATION SUCCESSFULL!");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "REGISTRATION FAILED");
        }

    }//GEN-LAST:event_Add_CustomerActionPerformed

    private void Manager_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_EmailActionPerformed

    private void Manager_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_AddressActionPerformed

    private void Manager_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_NameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Choice ch = new Choice(Manager_Email.getText());
        ch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmanager("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Customer;
    private javax.swing.JTextField Manager_Address;
    private javax.swing.JTextField Manager_Email;
    private javax.swing.JTextField Manager_Mobileno;
    private javax.swing.JTextField Manager_Name;
    private javax.swing.JTextField Manager_Password;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
