/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import static com.addcustomer.resize;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Joy
 */
public class CustomerProfile extends javax.swing.JFrame {
    public static int w=0,h=0;
    String filename = new String();
    String path = null;
    
    String Email;
    String C_out="NULL";
    
    Connection conn = null;
    //OraclePreparedStatement pst = null;
    OracleResultSet rs = null;

    /**
     * Creates new form CustomerProfile
     */
    public CustomerProfile(String newEmail) {
        
        
        initComponents();
        Email = newEmail;
        
        refresh();
        HistoryRefresh();
        setPic();
    }
    
    
    
     /*public CustomerProfile(String newEmail) {
        
        initComponents();
        Email = newEmail;
        refresh();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Profile_Customer_Name = new javax.swing.JTextField();
        Profile_Customer_Id = new javax.swing.JTextField();
        Profile_Customer_Mobileno = new javax.swing.JTextField();
        Profile_Customer_Address = new javax.swing.JTextField();
        Current_Pass = new javax.swing.JTextField();
        Profile_Customer_Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Check_out = new javax.swing.JButton();
        New_Pass = new javax.swing.JTextField();
        Profile_Customer_Gender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chng_pass_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Room_No = new javax.swing.JTextField();
        CheckIn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Historytable = new javax.swing.JTable();
        propic = new javax.swing.JLabel();
        imageAddress = new javax.swing.JLabel();
        picChoose = new javax.swing.JButton();
        upload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 434));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile_Customer_Name.setBackground(new java.awt.Color(153, 153, 255));
        Profile_Customer_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Profile_Customer_Name.setEnabled(false);
        Profile_Customer_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_Customer_NameActionPerformed(evt);
            }
        });
        Profile_Customer_Name.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Profile_Customer_NamePropertyChange(evt);
            }
        });
        jPanel1.add(Profile_Customer_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 160, 30));

        Profile_Customer_Id.setBackground(new java.awt.Color(153, 153, 255));
        Profile_Customer_Id.setEnabled(false);
        Profile_Customer_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_Customer_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Profile_Customer_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 160, 30));

        Profile_Customer_Mobileno.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(Profile_Customer_Mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 160, 30));

        Profile_Customer_Address.setBackground(new java.awt.Color(153, 153, 255));
        Profile_Customer_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_Customer_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Profile_Customer_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 160, 30));

        Current_Pass.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(Current_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 160, 30));

        Profile_Customer_Email.setBackground(new java.awt.Color(153, 153, 255));
        Profile_Customer_Email.setEnabled(false);
        jPanel1.add(Profile_Customer_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 30, 22));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 40, 22));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 50, 22));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 20, 22));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 30, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MY PROFILE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 109, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Update Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Id", "Mobile No", "Adress", "Gender", "Password", "Email", "MY_ROOM", "CHECK_IN_TIME", "PRO_PIC"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 10, 10));

        Check_out.setBackground(new java.awt.Color(102, 102, 255));
        Check_out.setText("Check Out");
        Check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_outActionPerformed(evt);
            }
        });
        jPanel1.add(Check_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 140, 30));

        New_Pass.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(New_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 160, 30));

        Profile_Customer_Gender.setBackground(new java.awt.Color(153, 153, 255));
        Profile_Customer_Gender.setEnabled(false);
        jPanel1.add(Profile_Customer_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 160, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 90, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("New Password:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        chng_pass_btn.setText("Change Password");
        chng_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chng_pass_btnActionPerformed(evt);
            }
        });
        jPanel1.add(chng_pass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 140, 30));

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 140, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("My Room");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 78, 22));

        Room_No.setEditable(false);
        Room_No.setBackground(new java.awt.Color(153, 153, 255));
        Room_No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Room_No.setEnabled(false);
        Room_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_NoActionPerformed(evt);
            }
        });
        Room_No.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Room_NoPropertyChange(evt);
            }
        });
        jPanel1.add(Room_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 160, 30));

        CheckIn.setBackground(new java.awt.Color(153, 153, 255));
        CheckIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CheckIn.setEnabled(false);
        jPanel1.add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check In");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 20));

        Historytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ROOM_NO", "CUSTOMER_NAME", "CUSTOMER_MOB", "CHECK_IN_TIME", "CHECK_OUT_TIME"
            }
        ));
        jScrollPane2.setViewportView(Historytable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 110, 100));

        propic.setBackground(new java.awt.Color(204, 204, 255));
        propic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        jPanel1.add(propic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        imageAddress.setForeground(new java.awt.Color(0, 153, 255));
        imageAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(imageAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        picChoose.setText("Choose Profile Picture");
        picChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picChooseActionPerformed(evt);
            }
        });
        jPanel1.add(picChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, -1));

        upload.setText("Upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel1.add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Profile_Customer_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_Customer_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_Customer_AddressActionPerformed

    private void Profile_Customer_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_Customer_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_Customer_IdActionPerformed

    private void Profile_Customer_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_Customer_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_Customer_NameActionPerformed

    private void Profile_Customer_NamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Profile_Customer_NamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_Customer_NamePropertyChange
    private static java.sql.Timestamp getCurrentTimeStamp() throws ParseException {

	java.util.Date today = new java.util.Date();
	return new java.sql.Timestamp(today.getTime());
        
    }
    
    private void Check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_outActionPerformed
        // TODO add your handling code here:
        if(CheckIn.getText().equals("NULL"))
        {
            JOptionPane.showMessageDialog(null, "You haven't booked any room yet!");
        }
        else
        {
            refresh();
        HistoryRefresh();
        C_out = Historytable.getValueAt(0, 4).toString();
        try{
        
        conn = JavaConnectivity.ConnecrDb();
        
        PreparedStatement pst = conn.prepareStatement("UPDATE CUSTOMER SET MY_ROOM = ?, CHECK_IN_TIME = ? WHERE C_EMAIL = ?");
        PreparedStatement pst1 = conn.prepareStatement("UPDATE ROOM SET REFEREED_MANAGER = ?, C_NAME = ?, C_MOBILENO = ?, R_STATUS = ? WHERE R_NO = ?");
        PreparedStatement pst2 = conn.prepareStatement("UPDATE HISTORY SET CHECK_OUT_TIME = ? WHERE R_NO = ? AND CUSTOMER_MOB = ? AND CHECK_IN_TIME=?");
        
	
        
        pst2.setString(1,getCurrentTimeStamp().toString());
        pst2.setString(2,Room_No.getText());
        pst2.setString(3,Profile_Customer_Mobileno.getText());
        pst2.setString(4,CheckIn.getText());
        
        
        pst1.setString(1,"NULL");
        pst1.setString(2,"NULL");
        pst1.setString(3,"NULL");
        pst1.setString(4,"Available");
        pst1.setString(5,Room_No.getText());
        
        
        pst.setString(1,"NULL");
        pst.setString(2,"NULL");
        pst.setString(3,Profile_Customer_Email.getText());
       
        
        pst.executeUpdate();
        pst1.executeUpdate();
        pst2.executeUpdate();

            
        
        pst.close();
        pst1.close();
        pst2.close();
        
        conn.close();
        
        
        
        JOptionPane.showMessageDialog(null, "Check Out Successfull!");
        
        
        
        refresh();
        HistoryRefresh();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "CheckOut FAILED");
        }
        
        }
        
    }//GEN-LAST:event_Check_outActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        conn = JavaConnectivity.ConnecrDb();
        
        PreparedStatement pst = conn.prepareStatement("UPDATE CUSTOMER SET C_MOBILENO = ?, C_ADDRESS = ? WHERE C_EMAIL = ?");
        
        
        pst.setString(1,Profile_Customer_Mobileno.getText());
        pst.setString(2,Profile_Customer_Address.getText());
        
        //System.out.println(imageAddress.getText());
        /*
        if(!imageAddress.getText().isEmpty())
        {
            filename = imageAddress.getText();
        
        }
        
        
        pst.setString(3, filename);
        */
        pst.setString(3,Profile_Customer_Email.getText());
           //System.out.println("1");
        
        pst.executeUpdate();
           //System.out.println("2");
        pst.close();
        conn.close();
        
        
        
        JOptionPane.showMessageDialog(null, "UPDATE SUCCESSFULL!");
        refresh();
        HistoryRefresh();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "UPDATE FAILED");
        }
    }                                        

    private void N_passActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chng_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chng_pass_btnActionPerformed
        // TODO add your handling code here:
        if(New_Pass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Blank Password Field!");
        }
        else if(New_Pass.getText().length() < 6)
        {
            JOptionPane.showMessageDialog(null, "Minimum Password Length: 6");
        }
        else if(!(jTable1.getValueAt(0, 5).toString().equals(Current_Pass.getText())))
        {
            JOptionPane.showMessageDialog(null, "Sorry! Current Password Wrong!");
        }
        else if(Current_Pass.getText().equals(New_Pass.getText()))
        {
            JOptionPane.showMessageDialog(null, "This password is already set!");
        }
        else if(jTable1.getValueAt(0, 5).toString().equals(Current_Pass.getText()))
        {
                    try{
        conn = JavaConnectivity.ConnecrDb();
        
        PreparedStatement pst = conn.prepareStatement("UPDATE CUSTOMER SET C_PASSWORD = ? WHERE C_ID = ? AND C_PASSWORD = ?");
        
        
        pst.setString(1,New_Pass.getText());
        pst.setString(2,Profile_Customer_Id.getText());
        pst.setString(3,Current_Pass.getText());
        
        
        
        
        
            pst.executeUpdate();
        
             pst.close();
             conn.close();
            JOptionPane.showMessageDialog(null, "PASSWORD UPDATED!");
            Current_Pass.setText("");
            New_Pass.setText("");
        
        
        refresh();
        HistoryRefresh();
        }
        catch(Exception e){
            
        }
        }

        
        
    }//GEN-LAST:event_chng_pass_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login l = new Login();
        l.status = 0;
        WellCome_Window wd = new WellCome_Window();
        wd.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Room_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_NoActionPerformed

    private void Room_NoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Room_NoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_NoPropertyChange
    public static ImageIcon resize(ImageIcon im, int w, int h)
    {
        BufferedImage bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D gd = (Graphics2D)bi.createGraphics();
        gd.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING,RenderingHints.VALUE_RENDER_QUALITY));
        gd.drawImage(im.getImage(), 0, 0, w, h, null);
        gd.dispose();
        return new ImageIcon(bi);
    }
    void setPic()
    {
        ImageIcon icon = new ImageIcon(filename);
        icon.getImage().flush();
        propic.setIcon(icon);            
    }
    private void picChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picChooseActionPerformed
        // TODO add your handling code here:
            w=0; h=0;
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            
            filename = f.getAbsolutePath();
            imageAddress.setText(filename);
            
            Image getAbsolutePath = null;
            
            ImageIcon icon = new ImageIcon(filename);
            Dimension imgSize = new Dimension(icon.getImage().getWidth(chooser), icon.getImage().getHeight(chooser));
            Dimension boundary = new Dimension(171, 220);
            getScaledDimension(imgSize, boundary);
            
            
            Image img1 = resize(new ImageIcon(filename),w, h).getImage();
            Image img2 = img1.getScaledInstance(w, h, Image.SCALE_SMOOTH);
            
            ImageIcon icon1 = new ImageIcon(img2);
            
            propic.setBounds(390, 40, w, h);
            //propic.setIcon(icon1);
            propic.setIcon(icon1);
            
        //writing
        
        BufferedImage bi = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = bi.createGraphics();
        // Draw img into bi so we can write it to file.
        g2.drawImage(img2, 0, 0, null);
        g2.dispose();
        
            // Now bi contains the img.
            // Note: img may have transparent pixels in it; if so, okay.
            // If not and you can use TYPE_INT_RGB you will get better
            // performance with it in the jvm.
        try {
            
/*            
//delete previous image
            Path imagesPath = Paths.get(filename);

            try {
                Files.delete(imagesPath);
            
            } catch (IOException e) {
                System.err.println("Unable to delete "+ imagesPath.toAbsolutePath().toString()+ " due to...");
                e.printStackTrace();
            }
  */              
            ImageIO.write(bi, "jpg", new File(path = ("C:\\Users\\Joy\\Documents\\NetBeansProjects\\DatabaseProject\\ProfilePictures\\"+Profile_Customer_Id.getText()+".jpg")));
            
            filename = path;
            imageAddress.setText(filename);
            
        } catch (IOException ex) {
            Logger.getLogger(addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_picChooseActionPerformed
    
    
    public static void getScaledDimension(Dimension imgSize, Dimension boundary) {

    int original_width = imgSize.width;
    int original_height = imgSize.height;
    int bound_width = boundary.width;
    int bound_height = boundary.height;
    int new_width = original_width;
    int new_height = original_height;

    // first check if we need to scale width
    if (original_width > bound_width) {
        //scale width to fit
        new_width = bound_width;
        //scale height to maintain aspect ratio
        new_height = (new_width * original_height) / original_width;
    }

    // then check if we need to scale even with the new height
    if (new_height > bound_height) {
        //scale height to fit instead
        new_height = bound_height;
        //scale width to maintain aspect ratio
        new_width = (new_height * original_width) / original_height;
    }
    w= new_width;
    h= new_height;
    //return new Dimension(new_width, new_height);
    }
    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        try{

        conn = JavaConnectivity.ConnecrDb();
        
        PreparedStatement pst = conn.prepareStatement("UPDATE CUSTOMER SET PRO_PIC = ? WHERE C_EMAIL = ?");
        
        pst.setString(1,imageAddress.getText());
        pst.setString(2,Profile_Customer_Email.getText());
        pst.executeUpdate();
        
        pst.close();
        conn.close();
        JOptionPane.showMessageDialog(null, "Picture Uploaded!");
       
        //setPic();
        refresh();
        HistoryRefresh();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_uploadActionPerformed
private void refresh(){
        setPic();                            
        try {
            conn = JavaConnectivity.ConnecrDb();
            //Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=MISHU;integratedSecurity=true");

            Statement statement = conn.createStatement();
            
            ResultSet rs = statement.executeQuery("select * from customer where C_EMAIL='" + Email + "'");
            
            ResultSetMetaData  rsmetadata = rs.getMetaData();
            int  columns = rsmetadata.getColumnCount();
            DefaultTableModel dtm = new DefaultTableModel();
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
            for(int  i= 1; i < columns+1; i++)
            {
                columns_name.addElement (rsmetadata.getColumnLabel(i));
            }

            dtm.setColumnIdentifiers(columns_name);
            while (rs.next())
            {
                data_rows = new Vector();
                for (int j = 1; j <columns+1; j++)
                {
                    data_rows.addElement(rs.getString(j)) ;
                }
                dtm.addRow(data_rows);

            }
            //System.out.println(data_rows);
            jTable1.setModel(dtm);
            
            Profile_Customer_Name.setText(jTable1.getValueAt(0, 1).toString());
            Profile_Customer_Id.setText(jTable1.getValueAt(0, 0).toString());
            Profile_Customer_Mobileno.setText(jTable1.getValueAt(0, 2).toString());
            Profile_Customer_Address.setText(jTable1.getValueAt(0, 3).toString());
            Profile_Customer_Gender.setText(jTable1.getValueAt(0, 4).toString());
            Profile_Customer_Email.setText(jTable1.getValueAt(0, 6).toString());
            Room_No.setText(jTable1.getValueAt(0, 7).toString());
            
            CheckIn.setText(jTable1.getValueAt(0, 8).toString());
            
            
            filename = jTable1.getValueAt(0, 9).toString();
            //System.out.println(filename);
            imageAddress.setText(filename);
            propic.setIcon(resize(new ImageIcon(filename),propic.getWidth(), propic.getHeight()));
            
            
            //pst.executeUpdate();
        
        //pst.close();
        conn.close();
        

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }


private void HistoryRefresh(){
                                             
        try {
            conn = JavaConnectivity.ConnecrDb();
            //Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=MISHU;integratedSecurity=true");

            //history
            Statement statement = conn.createStatement();
            
            ResultSet rs = statement.executeQuery("select * from History where CUSTOMER_MOB = '" + Profile_Customer_Mobileno.getText()+ "' ");
            
            ResultSetMetaData  rsmetadata = rs.getMetaData();
            int  columns = rsmetadata.getColumnCount();
            DefaultTableModel dtm = new DefaultTableModel();
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
            for(int  i= 1; i < columns+1; i++)
            {
                columns_name.addElement (rsmetadata.getColumnLabel(i));
            }

            dtm.setColumnIdentifiers(columns_name);
            while (rs.next())
            {
                data_rows = new Vector();
                for (int j = 1; j <columns+1; j++)
                {
                    data_rows.addElement(rs.getString(j)) ;
                }
                dtm.addRow(data_rows);

            }
            Historytable.setModel(dtm);
            
            
            //pst.executeUpdate();
        
        //pst.close();
        conn.close();
        

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerProfile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheckIn;
    private javax.swing.JButton Check_out;
    private javax.swing.JTextField Current_Pass;
    private javax.swing.JTable Historytable;
    private javax.swing.JTextField New_Pass;
    private javax.swing.JTextField Profile_Customer_Address;
    private javax.swing.JTextField Profile_Customer_Email;
    private javax.swing.JTextField Profile_Customer_Gender;
    private javax.swing.JTextField Profile_Customer_Id;
    private javax.swing.JTextField Profile_Customer_Mobileno;
    public javax.swing.JTextField Profile_Customer_Name;
    public javax.swing.JTextField Room_No;
    private javax.swing.JButton chng_pass_btn;
    private javax.swing.JLabel imageAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton picChoose;
    private javax.swing.JLabel propic;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
