/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Joy
 */
public class Login extends javax.swing.JFrame {
    public static int status = 0;
    Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;

    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        User_email = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Admin = new javax.swing.JRadioButton();
        Manager = new javax.swing.JRadioButton();
        Customer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        passAlert = new javax.swing.JLabel();
        emailAlert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 450));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 202, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 253, 65, 20));

        User_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_email.setToolTipText("enter email address");
        User_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_emailActionPerformed(evt);
            }
        });
        jPanel1.add(User_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 199, 157, -1));

        PASSWORD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PASSWORD.setToolTipText("enter password");
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });
        jPanel1.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 253, 157, -1));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 312, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Hotel Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 29, -1, -1));

        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        Manager.setForeground(new java.awt.Color(255, 255, 255));
        Manager.setText("Manager");
        Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerActionPerformed(evt);
            }
        });
        jPanel1.add(Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        Customer.setForeground(new java.awt.Color(255, 255, 255));
        Customer.setText("Customer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        jPanel1.add(Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 181, 284, -1));

        alert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 0, 0));
        alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 280, -1));

        passAlert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passAlert.setForeground(new java.awt.Color(255, 0, 0));
        passAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(passAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 150, -1));

        emailAlert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailAlert.setForeground(new java.awt.Color(255, 0, 0));
        emailAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(emailAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
        if(Customer.isSelected())
        {
            Admin.setSelected(false);
            Manager.setSelected(false);
            status = 3;
        }
        else if(!Customer.isSelected())
        {
            status = 0;
        }
    }//GEN-LAST:event_CustomerActionPerformed

    private void ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerActionPerformed
        // TODO add your handling code here:

        if(Manager.isSelected())
        {
            Admin.setSelected(false);
            Customer.setSelected(false);
            status = 2;
        }
        else if(!Manager.isSelected())
        {
            status = 0;
        }

    }//GEN-LAST:event_ManagerActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        if(Admin.isSelected())
        {
            Manager.setSelected(false);
            Customer.setSelected(false);
            status = 1;
        }
        else if(!Admin.isSelected())
        {
            status = 0;
        }
    }//GEN-LAST:event_AdminActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(status==0 && User_email.getText().isEmpty() && PASSWORD.getText().isEmpty())
        {
            alert.setText("Please select user type!");
            emailAlert.setText("Email is required!");
            passAlert.setText("Password is required!");
        }
        if(status==0)
        {
            alert.setText("Please select user type!");
        }
        if(status!=0)
        {
            alert.setText("");
        } 
        if(!User_email.getText().isEmpty())
        {
            if(PASSWORD.getText().isEmpty())
            {
                 passAlert.setText("Password is required!");
            }
            emailAlert.setText("");
        }
        if(!PASSWORD.getText().isEmpty())
        {
            if(User_email.getText().isEmpty())
            {
                 emailAlert.setText("Email is required!");
            }
            passAlert.setText("");
        }
        if(User_email.getText().isEmpty() && PASSWORD.getText().isEmpty())
        {
            emailAlert.setText("Email is required!");
            passAlert.setText("Password is required!");
        }
        
        if(User_email.getText().isEmpty())
        {
            emailAlert.setText("Email is required!");
        }
        if(PASSWORD.getText().isEmpty())
        {
            passAlert.setText("Password is required!");
        }
        
        if(status>0 && !User_email.getText().isEmpty() && !PASSWORD.getText().isEmpty())
        {
            conn = JavaConnectivity.ConnecrDb();
            try{
                String sql = new String();
                if(status==1)
                {
                    sql = "select * from admin where ADD_EMAIL=? and PASSWORD=?";
                }
                else if(status==2)
                {
                    sql = "select * from manager where M_EMAIL=? and M_PASSWORD=?";
                }
                else if(status==3)
                {
                    sql = "select * from customer where C_EMAIL=? and C_PASSWORD=?";
                }

                String Email= User_email.getText();
                pst = (OraclePreparedStatement) conn.prepareStatement(sql);
                pst.setString(1, User_email.getText());
                pst.setString(2,PASSWORD.getText());
                rs = (OracleResultSet) pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "The email and password was successfully verified");
                    if(status==1)
                    {
                        Choice c = new Choice(Email);
                        c.setVisible(true);
                    }
                    else if(status==2)
                    {
                        Manager_Profile mp = new Manager_Profile(Email);
                        mp.setVisible(true);
                    }
                    else if(status==3)
                    {
                        CustomerProfile cp = new CustomerProfile(Email);
                        cp.setVisible(true);
                    }

                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Invalid User");
                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void User_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin;
    private javax.swing.JRadioButton Customer;
    private javax.swing.JRadioButton Manager;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JTextField User_email;
    private javax.swing.JLabel alert;
    private javax.swing.JLabel emailAlert;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passAlert;
    // End of variables declaration//GEN-END:variables
}
