/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joy
 */
public class Manager_Profile extends javax.swing.JFrame {
    String Email;
    
    Connection conn = null;
    //OraclePreparedStatement pst = null;
    OracleResultSet rs = null;

    /**
     * Creates new form Manager_Profile
     */
    public Manager_Profile(String newEmail) {
        initComponents();
        Email = newEmail;
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Manager_Name = new javax.swing.JTextField();
        Manager_Id = new javax.swing.JTextField();
        Manager_Mobileno = new javax.swing.JTextField();
        Manager_Address = new javax.swing.JTextField();
        Manager_Email = new javax.swing.JTextField();
        C_pass = new javax.swing.JTextField();
        N_pass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manager_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Manager_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Manager_Name.setEnabled(false);
        Manager_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Manager_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 67, 160, 30));

        Manager_Id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Manager_Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Manager_Id.setToolTipText("");
        Manager_Id.setEnabled(false);
        Manager_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Manager_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 117, 160, 30));

        Manager_Mobileno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Manager_Mobileno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Manager_Mobileno.setToolTipText("Update Mobile Number");
        jPanel1.add(Manager_Mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 157, 160, 30));

        Manager_Address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Manager_Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Manager_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 207, 160, 30));

        Manager_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Manager_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Manager_Email.setEnabled(false);
        Manager_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Manager_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, 30));

        C_pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        C_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(C_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 160, 30));

        N_pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        N_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        N_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_passActionPerformed(evt);
            }
        });
        jPanel1.add(N_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 160, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("       Email:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 217, 50, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile No:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 167, -1, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("           Id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, 50, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 77, 50, 20));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 132, 33));

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 120, -1));

        jButton1.setText("Update  Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 119, -1));

        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "M_Name", "M_Id", "M_Mobile No", "M_Adress", "M_Email"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 247, 360, 150));

        jButton4.setText("Add Customer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 150, 30));

        jButton5.setText("Customer Check-in");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Manager_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_NameActionPerformed

    private void Manager_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_IdActionPerformed

    private void Manager_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_EmailActionPerformed

    private void N_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_passActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.status = 0;
        WellCome_Window wd = new WellCome_Window();
        wd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            conn = JavaConnectivity.ConnecrDb();

            PreparedStatement pst = conn.prepareStatement("UPDATE MANAGER SET M_PHONE = ?, M_ADDRESS = ? WHERE M_ID = ?");

            pst.setString(1,Manager_Mobileno.getText());
            pst.setString(2,Manager_Address.getText());
            pst.setInt(3,Integer.parseInt(Manager_Id.getText()));

            pst.executeUpdate();

            pst.close();
            conn.close();

            JOptionPane.showMessageDialog(null, "UPDATE SUCCESSFULL!");
            refresh();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "UPDATE FAILED");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            /*
            conn = JavaConnectivity.ConnecrDb();
        
        PreparedStatement pst = conn.prepareStatement("UPDATE CUSTOMER SET C_PASSWORD = ? WHERE C_ID = ? AND C_PASSWORD = ?");
        
        
        pst.setString(1,New_Pass.getText());
        pst.setString(2,Profile_Customer_Id.getText());
        pst.setString(3,Current_Pass.getText());
        
        
        
        if(New_Pass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Blank Password Field!");
        }
        else if(New_Pass.getText().length() < 6)
        {
            JOptionPane.showMessageDialog(null, "Minimum Password Length: 6");
        }
        else if(jTable1.getValueAt(0, 5).toString().equals(Current_Pass.getText()))
        {
            pst.executeUpdate();
        
             pst.close();
             conn.close();
            JOptionPane.showMessageDialog(null, "PASSWORD UPDATED!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Sorry! Current Password Wrong!");
        }
        
        refresh();
        }
        catch(Exception e){
            
        }
            */
            conn = JavaConnectivity.ConnecrDb();

            PreparedStatement pst = conn.prepareStatement("UPDATE MANAGER SET M_PASSWORD = ? WHERE M_ID = ? AND M_PASSWORD = ?");

            pst.setString(1,N_pass.getText());
            pst.setString(2,Manager_Id.getText());
            pst.setString(3,C_pass.getText());

            if(N_pass.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Blank Password Field!");
            }
            else if(N_pass.getText().length() < 6)
            {
                JOptionPane.showMessageDialog(null, "Minimum Password Length: 6");
            }
            else if(jTable1.getValueAt(0, 2).toString().equals(C_pass.getText()))
            {
                pst.executeUpdate();

                pst.close();
                conn.close();
                JOptionPane.showMessageDialog(null, "PASSWORD UPDATED!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry! Current Password Wrong!");
            }

            refresh();
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        addcustomer ac = new addcustomer(Email);
        ac.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Room r = new Room(Manager_Email.getText());
        r.setVisible(true);
        this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
private void refresh(){
                                             
        try {
            conn = JavaConnectivity.ConnecrDb();
            //Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=MISHU;integratedSecurity=true");

            Statement statement = conn.createStatement();
            
            ResultSet rs = statement.executeQuery("select * from manager where M_EMAIL='" + Email + "'");
            
            ResultSetMetaData  rsmetadata = rs.getMetaData();
            int  columns = rsmetadata.getColumnCount();
            DefaultTableModel dtm = new DefaultTableModel();
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
            for(int  i= 1; i < columns+1; i++)
            {
                columns_name.addElement (rsmetadata.getColumnLabel(i));
            }

            dtm.setColumnIdentifiers(columns_name);
            while (rs.next())
            {
                data_rows = new Vector();
                for (int j = 1; j <columns+1; j++)
                {
                    data_rows.addElement(rs.getString(j)) ;
                }
                dtm.addRow(data_rows);

            }
            jTable1.setModel(dtm);
            Manager_Name.setText(jTable1.getValueAt(0, 1).toString());
            Manager_Id.setText(jTable1.getValueAt(0, 0).toString());
            Manager_Mobileno.setText(jTable1.getValueAt(0, 2).toString());
            Manager_Address.setText(jTable1.getValueAt(0, 3).toString());
            Manager_Email.setText(jTable1.getValueAt(0, 4).toString());
            
           
            
            
            //pst.executeUpdate();
        
        //pst.close();
        conn.close();
        

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Profile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_pass;
    private javax.swing.JTextField Manager_Address;
    private javax.swing.JTextField Manager_Email;
    private javax.swing.JTextField Manager_Id;
    private javax.swing.JTextField Manager_Mobileno;
    private javax.swing.JTextField Manager_Name;
    private javax.swing.JTextField N_pass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
